### ISSUE TITLE
Jdamour from Massdrop

### ISSUE THREAD

**Issue by jasondamour** [LastContinue/ctrl-info#1]
Continuing our Last conversation (pardon the pun), I have a Late 2016 MacbookPro 13" touchbar. I'm going to test the force NKRO, and then see if I can reassign it (thats the reason i'm even trying qmk

**Comment by jasondamour** [comment]
Reading the docs, I see that compiliing with the qmk make file creates a .hex file, but the massdrop compiler makes a .bin file? Is there another way to compile

**Comment by jasondamour** [comment]
Lol nvm

**Comment by jasondamour** [comment]
So update: Force NKRO does not work after reboot with my computer as well. Disabling that, but reassigned the toggle nkro key

**Comment by LastContinue** [comment]
Wow, sorry, I _just_ now saw this! 🙇‍♂️ (I guess I need to make sure GitHub emails me on stuff like this 🤔)

Thanks for doing the investigation on this! 

Since `SEND_STRING` and other macro fixes have found their way into QMK master, the need to have NKRO on by default is really lessened (for me) 

I also figure out how to do it be default via keymaps, so you could have like a Windows map that turns it on, and a Mac map that turns it off. I think I documented that in the Wiki, but I've gotten a bit behind on keeping that up to date!

I really appreciate you filing an issue here, and again, apologizes for my late reply 💦
