### ISSUE TITLE
CTRL-LDR Error on macOS Catalina (10.15.5)

### ISSUE THREAD

**Issue by lynng** [LastContinue/ctrl-info#4]
I see it's been a while since this project has had any updates.

CTRL Bootstrap ran fine (after allowing a security exception) and downloaded the ctrl-ldr.sh to ~/Desktop and set it to be executable. On running CTRL-LDR, I got "The action "Run AppleScript" encountered an error: "Can't get POSIX path of {}."

I then ran `./ctrl-ldr.sh massdrop_ctrl_config-myconfig.bin`, which executed mdloader fine. Mdloader didn't find my keyboard after resetting it, though. The lights turned off, but I got the dreaded "Error: Could not find a valid device port!" so it's back to scouring the howto thread on Drop.com.

Posting to let @LastContinue know the AppleScript is broken on Catalina.

**Comment by LastContinue** [comment]
Thanks for the interest!

 You're right, I haven't updated this in quite sometime, mostly because it _seems_ like everything still works, but maybe not!

First, I realize I should be more clear about the nature CTRL-LDR: You don't actually _run_ CTLR-LDR (like double click, etc), it's merely a shortcut that you need to drag your files onto (like how'd you'd drag something into the Trash). 

Try dragging your `massdrop_ctrl_config-myconfig.bin` onto the CTRL-LDR and tell me what it shows. There's still a chance it's broken, but that `"Can't get POSIX path of {}."` is what I used to get when I'd try to start it without any `.bin` file for it to work on. (here `{}` means "no file", or at least it used to)

`"Error: Could not find a valid device port!"` 

My brand new CTRL hi-pro had the same issue. I've had several of these boards and not had that issue. Either 
1. 'Drop needs to update mdloader (I would not hold my breath)
1. Board is broken. 

I already opened a ticket with them. We'll see what they have to say.

Let me know if you find anything helpful though!

**Comment by lynng** [comment]
Thanks for the reply. You're right in that I totally misunderstood the instructions, and was trying to open CTRL-LDR like an app. I was expecting a window that I'd then drag the `.bin` file onto.

I did get my new high-profile CTRL (arrived today!) working. I got an updated mdloader_common.c from https://github.com/Massdrop/mdloader/pull/25 and recompiled, then ran it directly from the command line according to Massdrop's usual instructions. It recognized the CTRL immediately.

**Comment by lynng** [comment]
You may also want to add that to run CTRL Bootstrap on Catalina, you have ctrl-click and Open in order for the security dialog to give you the `Open` button. If you just double-click, it gives only "Move to trash" and "Cancel". Or, remove the quarantine attribute, but the idea is to help people avoid the terminal.

Similarly, I just tested dragging the `.bin` file onto the CTRL-LDR, and I got the security dialog that doesn't allow Open. But, at least didn't get the `"Can't get POSIX path of {}."` error. Solved by first ctrl-clicking and selecting Open, then `Open` again as above ... which gives the POSIX error. Dismiss that dialog, then do the drag-and-drop of the `.bin` onto the CTRL-LDR. 

Then there's another security dialog because `"CTRL-LDR" wants access to control "Terminal"` which you have to `Allow`. I see it looking for the keyboard, but because the version of mdloader you download doesn't have the fix in my previous comment, it fails.

**Comment by LastContinue** [comment]
> Then there's another security dialog because `"CTRL-LDR" wants access to control "Terminal"` which you have to `Allow`. I see it looking for the keyboard, but because the version of mdloader you download doesn't have the fix in my previous comment, it fails.

Ah yeah, security wasn't as granular in MacOS when I first made these things years ago. I like your idea about it opening a window and being able to drag into there. I might see if there's an easy way to do that. Thanks for the feedback. (I don't suppose you have any insights on improving the Powershell version do you? 😉)

>I did get my new high-profile CTRL (arrived today!) working. I got an updated mdloader_common.c from Massdrop/mdloader#25 and recompiled, then ran it directly from the command line according to Massdrop's usual instructions. It recognized the CTRL immediately.

Wow, thanks so much. This totally worked.

Do you have a link to the MD thread where you found this? I didn't bother going into any of the MD threads because
1. Which one? Every time they do another run of these boards, a new thread opens up
1. They are very cyclical in nature, and usually never that technical. The few posts I found years ago about doing key-by-key stuff were like they were done by aliens who visited the planet and then left. 

I'd have no problem building and hosting my own (fixed) versions of mdloader (I will be very surprised if that PR ever gets merged. Spend long enough on those MD threads and you get pretty jaded about any MD staff ever actually _doing anything_ support related), but I have no idea how to compile it in Windows 😆 (in fact, due to COVID I might not even be able to get my hands on a Windows machine... 🤔)

Well I'll at least put a disclaimer in the README until _something_ happens. 

Thanks again for pointing me to that fix, and I'll see if there's anything I can do to make that drag-and-drop less confusing. 🙇‍♂️

**Comment by lynng** [comment]
I’m not sure if it’s in the MD thread or not. I found by checking the mdloader Issues page, and someone had posted a thread 9 days ago with the same problem I had on Mac, and eventually someone linked to the pull request with the fix. That issue discussion is https://github.com/Massdrop/mdloader/issues/24
